// data actions
export const RESERVATION_ADD = 'RESERVATION_ADD';
export const RESERVATION_REMOVE = 'RESERVATION_REMOVE';
export const RESERVATION_PRATICIEN_FILTER_SET = 'RESERVATION_PRATICIEN_FILTER_SET';
export const RESERVATION_PRATICIEN_FILTER_UNSET = 'RESERVATION_PRATICIEN_FILTER_UNSET';
export const RESERVATION_CURRENT_SET = 'RESERVATION_CURRENT_SET';
export const RESERVATION_CURRENT_UNSET = 'RESERVATION_CURRENT_UNSET';
export const CURRENT_USER_SET = 'CURRENT_USER_SET';
export const CURRENT_USER_UNSET = 'CURRENT_USER_UNSET';
export const PRATICIENS_SET = 'PRATICIENS_SET';
export const PRATICIENS_UNSET = 'PRATICIENS_SET';


// network actions
//

export const LOAD_PRATICIENS = 'LOAD_PRATICIENS';
export const LOAD_RESERVATIONS = 'LOAD_RESERVATIONS';
export const LOAD_RESERVATION = 'LOAD_RESERVATION';
export const SAVE_RESERVATION = 'SAVE_RESERVATION';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';
export const SAVE_USER = 'SAVE_USER';
